version: '3.4'

services:
  webapi:
    image: DashboardDb
    build:
    context: .
    dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - postgres

    postgres:
      image: postgres:16
      environment:
      POSTGRES_DB: WidgetDB
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password123
      ports:
        - "5432:5432"