// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Persistance;

#nullable disable

namespace Dashboard.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250817082940_InitWidget")]
    partial class InitWidget
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Models.ImageWidget", b =>
                {
                    b.Property<Guid>("WidgetId")
                        .HasColumnType("uuid");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("WidgetId");

                    b.ToTable("ImageWidgets");
                });

            modelBuilder.Entity("Models.TextWidget", b =>
                {
                    b.Property<Guid>("WidgetId")
                        .HasColumnType("uuid");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("WidgetId");

                    b.ToTable("TextWidgets");
                });

            modelBuilder.Entity("Models.Widget", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Columns")
                        .HasColumnType("integer");

                    b.Property<int>("PositionX")
                        .HasColumnType("integer");

                    b.Property<int>("PositionY")
                        .HasColumnType("integer");

                    b.Property<int>("Rows")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Widgets");
                });

            modelBuilder.Entity("Models.ImageWidget", b =>
                {
                    b.HasOne("Models.Widget", "Widget")
                        .WithOne("ImageWidget")
                        .HasForeignKey("Models.ImageWidget", "WidgetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Widget");
                });

            modelBuilder.Entity("Models.TextWidget", b =>
                {
                    b.HasOne("Models.Widget", "Widget")
                        .WithOne("TextWidget")
                        .HasForeignKey("Models.TextWidget", "WidgetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Widget");
                });

            modelBuilder.Entity("Models.Widget", b =>
                {
                    b.Navigation("ImageWidget");

                    b.Navigation("TextWidget");
                });
#pragma warning restore 612, 618
        }
    }
}
