// <auto-generated />
using System;
using System.Collections.Generic;
using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Persistance;

#nullable disable

namespace Dashboard.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250826073247_RecreateDatabase")]
    partial class RecreateDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Models.ChartWidget", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("BackgroundColor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("BorderWidth")
                        .HasColumnType("integer");

                    b.Property<double>("CategoryPercentage")
                        .HasColumnType("double precision");

                    b.Property<JsonDocument>("ChartData")
                        .HasColumnType("jsonb");

                    b.Property<JsonDocument>("ChartOptions")
                        .HasColumnType("jsonb");

                    b.Property<string>("ChartType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.PrimitiveCollection<List<string>>("CsvHeaders")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("CsvRawData")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("ShowGrid")
                        .HasColumnType("boolean");

                    b.Property<bool>("ShowLegend")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("ChartWidgets");
                });

            modelBuilder.Entity("Models.ImageWidget", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("PreviewUrl")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ImageWidgets");
                });

            modelBuilder.Entity("Models.TableWidget", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<JsonDocument>("ColumnsTable")
                        .HasColumnType("jsonb");

                    b.Property<JsonDocument>("GridApi")
                        .HasColumnType("jsonb");

                    b.Property<JsonDocument>("RowsTable")
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.ToTable("TableWidgets");
                });

            modelBuilder.Entity("Models.TextWidget", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("HtmlContent")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("TextWidgets");
                });

            modelBuilder.Entity("Models.Widget", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Columns")
                        .HasColumnType("integer");

                    b.Property<int>("PositionX")
                        .HasColumnType("integer");

                    b.Property<int>("PositionY")
                        .HasColumnType("integer");

                    b.Property<int>("Rows")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Widgets");
                });

            modelBuilder.Entity("Models.ChartWidget", b =>
                {
                    b.HasOne("Models.Widget", "Widget")
                        .WithOne("ChartWidget")
                        .HasForeignKey("Models.ChartWidget", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Widget");
                });

            modelBuilder.Entity("Models.ImageWidget", b =>
                {
                    b.HasOne("Models.Widget", "Widget")
                        .WithOne("ImageWidget")
                        .HasForeignKey("Models.ImageWidget", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Widget");
                });

            modelBuilder.Entity("Models.TableWidget", b =>
                {
                    b.HasOne("Models.Widget", "Widget")
                        .WithOne("TableWidget")
                        .HasForeignKey("Models.TableWidget", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Widget");
                });

            modelBuilder.Entity("Models.TextWidget", b =>
                {
                    b.HasOne("Models.Widget", "Widget")
                        .WithOne("TextWidget")
                        .HasForeignKey("Models.TextWidget", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Widget");
                });

            modelBuilder.Entity("Models.Widget", b =>
                {
                    b.Navigation("ChartWidget");

                    b.Navigation("ImageWidget");

                    b.Navigation("TableWidget");

                    b.Navigation("TextWidget");
                });
#pragma warning restore 612, 618
        }
    }
}
